# Generated by Django 3.1.5 on 2021-01-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='petpicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petpicker_title', models.CharField(max_length=200)),
                ('petpicker_content', models.TextField()),
                ('petpicker_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
