# Generated by Django 3.1.5 on 2021-01-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpicker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petpicker',
            name='petpicker_content',
        ),
        migrations.RemoveField(
            model_name='petpicker',
            name='petpicker_published',
        ),
        migrations.RemoveField(
            model_name='petpicker',
            name='petpicker_title',
        ),
        migrations.AddField(
            model_name='petpicker',
            name='Init_Price',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
