# Generated by Django 3.1.5 on 2021-01-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpicker', '0003_auto_20210113_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpicker',
            name='petpicker_Submit',
            field=models.BooleanField(default=False),
        ),
    ]
