# Generated by Django 3.1.5 on 2021-01-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpicker', '0004_petpicker_petpicker_submit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='petpicker',
            new_name='petpicker_Model',
        ),
    ]
