# Generated by Django 3.1.5 on 2021-01-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpicker', '0005_auto_20210113_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='petpicker_Model',
        ),
    ]
