# Generated by Django 3.1.5 on 2021-01-16 20:22

from django.db import migrations, models
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('petpicker', '0010_auto_20210115_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fig_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot1', django_matplotlib.fields.MatplotlibFigureField()),
                ('plot2', django_matplotlib.fields.MatplotlibFigureField()),
                ('plot3', django_matplotlib.fields.MatplotlibFigureField()),
                ('plot4', django_matplotlib.fields.MatplotlibFigureField()),
                ('plot5', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
