# Generated by Django 3.1.5 on 2021-01-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpicker', '0012_auto_20210116_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fig_model',
            name='plot1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fig_model',
            name='plot2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fig_model',
            name='plot3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fig_model',
            name='plot4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fig_model',
            name='plot5',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
