# Generated by Django 3.1.5 on 2021-01-16 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpicker', '0013_auto_20210116_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fig_Model',
        ),
    ]
